[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type=["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.25"
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = "0.1"

[dev-dependencies]
rstest = "0.18"